Module2 task2
htmlacademy-adaptive/1859921-cat-energy-24 pull request #9
Opened 2021-12-04 12:16 UTC by EkaterinaDmitr

2021-12-04 15:12 UTC, sealeye requested changes
В основном нужно кнопки заменить на ссылки и для одинаково выглядящих элементов сделать общие классы.

2021-12-04 15:12 UTC, sealeye commented on source/catalog.html
> +              <button class="product__button">заказать</button>
Тут лучше сделать ссылку, чтобы переходить на страницу продукта

2021-12-04 15:12 UTC, sealeye commented on source/catalog.html
> +              <button class="product__button">показать все</button>
Тут тоже лучше ссылка

2021-12-04 15:12 UTC, sealeye commented on source/catalog.html
> +              <button class="dopproduct__button">заказать</button>
И тут нужна ссылка

2021-12-04 15:12 UTC, sealeye commented on source/form.html
> +            <fieldset class="filter__user-data filter__fieldset">
У одного и того же тега может быть только один класс элемента от блока, не может быть два элемента одного и того же блока. Второй элемент скорее тянет на модификатор.

2021-12-04 15:12 UTC, sealeye commented on source/form.html
> +                    <label class="filter__user-data-label" for="name">Имя:*</label>
Все лейблы на странице имеют одинаковый вид и значит им можно задать одинаковый класс и смиксовать его с классом элемента.

2021-12-04 15:12 UTC, sealeye commented on source/form.html
> +              <legend class="filter__user-contacts-title">Контактные данные (владельца кота)</legend>
Все заголовки тоже должны иметь общий класс

2021-12-05 18:23 UTC, sealeye commented
Нет исправлений с прошлой итерации

2021-12-05 18:52 UTC, EkaterinaDmitr commented
исправления

2021-12-06 21:06 UTC, merged